site_name: Catálogo DAX OBZ
site_url: https://faturasgenesys.github.io/obz_dax_site/
use_directory_urls: false

theme:
  name: material
  language: pt
  palette:
    primary: blue grey
    accent: light blue
  features:
    - navigation.instant
    - navigation.expand
    - search.highlight

nav:
  - Início: index.md
  - Catálogo: _Catálogo_DAX_OBZ.md
  - Medidas:
      - Medidas/: Medidas/
